name: Playwright Tests
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    container:
      image: mcr.microsoft.com/playwright:v1.40.0-jammy
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: yarn

    - name: Install playwright chromium
      run: yarn playwright install chromium --with-deps

    - name: Run Playwright tests
      run: xvfb-run npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} --project='chromium' --trace on -j 1

    - name: Publish Test Summary Results
      if: ${{ !cancelled() }}
      run: npx github-actions-ctrf ctrf/ctrf-report.json
      continue-on-error: true

    - name: Upload ctrf report to GitHub Actions Artifacts
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      continue-on-error: true
      with:
        name: ctrf-report-${{ matrix.shardIndex }}
        path: ctrf
        retention-days: 1

    - name: Upload blob report to GitHub Actions Artifacts
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      continue-on-error: true
      with:
        name: blob-report-${{ matrix.shardIndex }}
        path: blob-report
        retention-days: 1
  merge-reports:
      # Merge reports after playwright-tests, even if some shards have failed
      if: ${{ !cancelled() }}
      needs: [playwright-tests]

      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn

#      - name: Download blob reports from GitHub Actions Artifacts
#        uses: actions/download-artifact@v4
#        continue-on-error: true
#        with:
#          path: ctrf
#          pattern: ctrf-report-*
#          merge-multiple: true
#
#      - name: Merge into JSON Report
#        run: npx playwright merge-reports --reporter json ./ctrf
#
#      - name: Upload ctrf report to GitHub Actions Artifacts
#        if: ${{ !cancelled() }}
#        uses: actions/upload-artifact@v4
#        continue-on-error: true
#        with:
#          name: json-report--attempt-${{ github.run_attempt }}
#          path: ctrf
#          retention-days: 1

      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          path: all-blob-reports
          pattern: blob-report-*
          merge-multiple: true

      - name: Merge into HTML Report
        run: npx playwright merge-reports --reporter html ./all-blob-reports

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: html-report--attempt-${{ github.run_attempt }}
          path: playwright-report
          retention-days: 14